export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const CLEAN_UP_REGISTER_PROCESS = "CLEAN_UP_REGISTER_PROCESS";

export const DARK_MODE = "DARK_MODE";
export const LIGHT_MODE = "LIGHT_MODE";

export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";

export const REQUEST_USER_PROFILE = "REQUEST_USER_PROFILE";
export const SUCCESS_USER_PROFILE = "SUCCESS_USER_PROFILE";
export const FAIL_USER_PROFILE = "FAIL_USER_PROFILE";

export const REQUEST_USER_TOKEN = "REQUEST_USER_TOKEN";
export const SUCCESS_USER_TOKEN = "SUCCESS_USER_TOKEN";
export const FAIL_USER_TOKEN = "FAIL_USER_TOKEN";
